from sqlalchemy import Column, String, Text, DateTime, ForeignKey, JSON, Date, Integer
from sqlalchemy.orm import relationship, declarative_base
from datetime import datetime

Base = declarative_base()

def get_utc_now():
    return datetime.utcnow()

class Client(Base):
    __tablename__ = "clients"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, unique=True, index=True)
    
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    
    # Relationships
    users = relationship("User", back_populates="client")
    briefs = relationship("Brief", back_populates="client")

class Agency(Base):
    __tablename__ = "agencies"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, unique=True, index=True)
    
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    
    # Relationships
    users = relationship("User", back_populates="agency", foreign_keys="[User.agency_id]")
    plans = relationship("AgencyPlan", back_populates="agency")

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    email = Column(String, unique=True, index=True)
    password = Column(String) 
    name = Column(String, nullable=True)
    role = Column(String) # "DS_GROUP" or "AGENCY"
    
    # Foreign Keys
    client_id = Column(Integer, ForeignKey("clients.id"), nullable=True)
    agency_id = Column(Integer, ForeignKey("agencies.id"), nullable=True)
    
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    
    # Relationships
    client = relationship("Client", back_populates="users", foreign_keys=[client_id])
    agency = relationship("Agency", back_populates="users", foreign_keys=[agency_id])

    @property
    def agency_name(self):
        return self.agency.name if self.agency else None

class Brief(Base):
    __tablename__ = "briefs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    client_id = Column(Integer, ForeignKey("clients.id"))
    brand_name = Column(String, index=True)
    division = Column(String)
    creative_name = Column(String)
    objective = Column(Text)
    brief_type = Column(String)
    total_budget = Column(String)
    start_date = Column(Date)
    end_date = Column(Date)
    
    # Status: ACTIVE, COMPLETED
    status = Column(String, default="ACTIVE")
    
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    updated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Production Fields
    demographics_age = Column(String, nullable=True)
    demographics_gender = Column(String, nullable=True)
    demographics_nccs = Column(String, nullable=True)
    demographics_etc = Column(String, nullable=True)
    psychographics = Column(Text, nullable=True)
    key_markets = Column(Text, nullable=True)
    p1_markets = Column(Text, nullable=True)
    p2_markets = Column(Text, nullable=True)
    edit_durations = Column(String, nullable=True)
    acd = Column(String, nullable=True)
    dispersion = Column(String, nullable=True)
    advertisement_link = Column(String, nullable=True)
    creative_languages = Column(String, nullable=True)
    scheduling_preference = Column(Text, nullable=True)
    miscellaneous = Column(Text, nullable=True)
    remarks = Column(Text, nullable=True)
    
    # Relationships
    client = relationship("Client", back_populates="briefs")
    agency_plans = relationship("AgencyPlan", back_populates="brief")
    
    creator = relationship("User", foreign_keys=[created_by])
    updater = relationship("User", foreign_keys=[updated_by])

class AgencyPlan(Base):
    __tablename__ = "agency_plans"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    brief_id = Column(Integer, ForeignKey("briefs.id"))
    agency_id = Column(Integer, ForeignKey("agencies.id"))
    
    # Status: "DRAFT", "PENDING_REVIEW", "ACCEPTED", "REJECTED"
    status = Column(String, default="DRAFT") 
    version_number = Column(Integer, default=1)
    plan_file_name = Column(String, nullable=True)
    plan_file_url = Column(String, nullable=True)
    submitted_at = Column(DateTime, nullable=True)
    
    submitted_at = Column(DateTime, nullable=True)
    
    # New Fields for Agency Workflow (GCS & Mapping)
    raw_file_path = Column(String, nullable=True)       # Path to the raw uploaded file
    flat_file_path = Column(String, nullable=True)      # Path to the flat file generated by External Service
    validated_column_file_path = Column(String, nullable=True) # Path after Column Validation
    validated_row_file_path = Column(String, nullable=True)    # Path after Row Validation (Future)
    ai_mappings = Column(JSON, nullable=True)           # Mappings suggested by AI
    human_mappings = Column(JSON, nullable=True)        # Mappings confirmed by User
    
    created_at = Column(DateTime, default=get_utc_now)
    updated_at = Column(DateTime, default=get_utc_now, onupdate=get_utc_now)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    updated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    # Relationships
    brief = relationship("Brief", back_populates="agency_plans")
    agency = relationship("Agency", back_populates="plans")
    history = relationship("HistoryTrail", back_populates="agency_plan")
    
    creator = relationship("User", foreign_keys=[created_by])
    updater = relationship("User", foreign_keys=[updated_by])

    @property
    def agency_name(self):
        return self.agency.name if self.agency else ""

class HistoryTrail(Base):
    __tablename__ = "history_trail"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    agency_plan_id = Column(Integer, ForeignKey("agency_plans.id"))
    action = Column(String) 
    
    user_id = Column(Integer, ForeignKey("users.id")) 
    
    details = Column(Text, nullable=True)
    comment = Column(Text, nullable=True)
    
    created_at = Column(DateTime, default=get_utc_now)
    
    # Relationships
    agency_plan = relationship("AgencyPlan", back_populates="history")
    user = relationship("User")

    @property
    def user_name(self):
        return self.user.name if self.user else "Unknown"
