"""Refactor agency plan file paths retry

Revision ID: 5a4247114d27
Revises: fb338310c7a8
Create Date: 2026-02-05 17:26:43.779800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4247114d27'
down_revision: Union[str, Sequence[str], None] = 'fb338310c7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_plans', sa.Column('raw_file_path', sa.String(), nullable=True))
    op.add_column('agency_plans', sa.Column('flat_file_path', sa.String(), nullable=True))
    op.add_column('agency_plans', sa.Column('validated_column_file_path', sa.String(), nullable=True))
    op.add_column('agency_plans', sa.Column('validated_row_file_path', sa.String(), nullable=True))
    op.add_column('agency_plans', sa.Column('ai_mappings', sa.JSON(), nullable=True))
    op.add_column('agency_plans', sa.Column('human_mappings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_plans', 'human_mappings')
    op.drop_column('agency_plans', 'ai_mappings')
    op.drop_column('agency_plans', 'validated_row_file_path')
    op.drop_column('agency_plans', 'validated_column_file_path')
    op.drop_column('agency_plans', 'flat_file_path')
    op.drop_column('agency_plans', 'raw_file_path')
    # ### end Alembic commands ###
