"""Initial migration

Revision ID: 8f5032232a5d
Revises: 
Create Date: 2026-02-04 17:55:02.692320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5032232a5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('creative_name', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('brief_type', sa.String(), nullable=True),
    sa.Column('total_budget', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('demographics_age', sa.String(), nullable=True),
    sa.Column('demographics_gender', sa.String(), nullable=True),
    sa.Column('demographics_nccs', sa.String(), nullable=True),
    sa.Column('demographics_etc', sa.String(), nullable=True),
    sa.Column('psychographics', sa.Text(), nullable=True),
    sa.Column('key_markets', sa.Text(), nullable=True),
    sa.Column('p1_markets', sa.Text(), nullable=True),
    sa.Column('p2_markets', sa.Text(), nullable=True),
    sa.Column('edit_durations', sa.String(), nullable=True),
    sa.Column('acd', sa.String(), nullable=True),
    sa.Column('dispersion', sa.String(), nullable=True),
    sa.Column('advertisement_link', sa.String(), nullable=True),
    sa.Column('creative_languages', sa.String(), nullable=True),
    sa.Column('scheduling_preference', sa.Text(), nullable=True),
    sa.Column('miscellaneous', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_brand_name'), 'briefs', ['brand_name'], unique=False)
    op.create_table('agency_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('plan_file_name', sa.String(), nullable=True),
    sa.Column('plan_file_url', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_plan_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_plan_id'], ['agency_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_trail')
    op.drop_table('agency_plans')
    op.drop_index(op.f('ix_briefs_brand_name'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
